version: '3.7'
services:
  mysql:
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: app
    ports:
      - '3306:3306'

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - '5432:5432'

  node:
    image: node:16-alpine
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator:/home/node/app
    ports:
      - '9988:9999'
    command: npm start